---
title: "Course-Project-1"
author: "Muha Abdullah Al Pavel"
date: "9/18/2021"
output: html_document
---

There are several files in this repository


1.R script for making assignment plot
2.PNG image files which represent plots.

I using Dataset:Electric power consumption [20Mb]

The following descriptions of the 9 variables in the dataset are taken from the UCI web site:

1.Date: Date in format dd/mm/yyyy
2.Time: time in format hh:mm:ss
3.Global_active_power: household global minute-averaged active power (in kilowatt)
4.Global_reactive_power: household global minute-averaged reactive power (in kilowatt)
5.Voltage: minute-averaged voltage (in volt)
6.Global_intensity: household global minute-averaged current intensity (in ampere)
7.Sub_metering_1: energy sub-metering No. 1 (in watt-hour of active energy). It corresponds to the kitchen, containing mainly a dishwasher, an oven and a microwave (hot plates are not electric but gas powered).
8.Sub_metering_2: energy sub-metering No. 2 (in watt-hour of active energy). It corresponds to the laundry room, containing a washing-machine, a tumble-drier, a refrigerator and a light.
9.Sub_metering_3: energy sub-metering No. 3 (in watt-hour of active energy). It corresponds to an electric water-heater and an air-conditioner.

#Operation: I have done here
1.Download Dataset
2.Fork and clone the following GitHub repository: [https://github.com/rdpeng/ExData_Plotting1] into [https://github.com/PavelMAA/ExData_Plotting1.git]
2.Load data and extract data from 2007-2-1 to 2007-2-2
3.Modify variables classes appropriate for making plots
4.Make plots and save plots